spring:
  datasource:
    url: jdbc:postgresql://db:5432/walletdb
    username: walletuser
    password: walletpass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect