name: wallet-service-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-export-spec:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.7-dind
        options: --privileged
        ports:
          - 5432:5432

    env:
      DOCKER_HOST: tcp://localhost:2375
      TESTCONTAINERS_RYUK_DISABLED: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Grant permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build and Test
        run: ./gradlew clean test bootJar

      - name: Run app and extract OpenAPI spec
        run: |
          java -Dspring.profiles.active=dev -jar build/libs/*.jar &
          APP_PID=$!
          echo "Waiting for app startup..."
          sleep 15
          curl --fail http://localhost:8080/v3/api-docs.yaml -o openapi.yaml
          kill $APP_PID

      - name: Upload OpenAPI spec
        uses: actions/upload-artifact@v4
        with:
          name: openapi-spec
          path: openapi.yaml
