name: wallet-service-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-export-spec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build and Test
        run: ./gradlew clean test bootJar

      - name: Run app and extract OpenAPI spec
        run: |
          java -jar build/libs/*.jar &
          APP_PID=$!
          echo "Waiting for app startup..."
          sleep 15
          curl --fail http://localhost:8080/v3/api-docs.yaml -o openapi.yaml
          kill $APP_PID

      - name: Upload OpenAPI spec
        uses: actions/upload-artifact@v4
        with:
          name: openapi-spec
          path: openapi.yaml