name: wallet-service-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # JOB 1: Build and run all tests
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.7-dind
        options: --privileged
        ports:
          - 5432:5432

    env:
      DOCKER_HOST: tcp://localhost:2375
      TESTCONTAINERS_RYUK_DISABLED: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Grant Gradle wrapper permission
        run: chmod +x ./gradlew

      - name: Build and run tests
        run: ./gradlew clean test bootJar

      - name: Upload JAR for reuse
        uses: actions/upload-artifact@v4
        with:
          name: wallet-jar
          path: build/libs/*.jar

  # JOB 2: Run app and extract OpenAPI spec
  export-openapi-spec:
    runs-on: ubuntu-latest
    needs: build-and-test

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: walletdb
          POSTGRES_USER: walletuser
          POSTGRES_PASSWORD: walletpass

    env:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/walletdb
      SPRING_DATASOURCE_USERNAME: walletuser
      SPRING_DATASOURCE_PASSWORD: walletpass

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Download JAR from previous job
        uses: actions/download-artifact@v4
        with:
          name: wallet-jar
          path: build/libs

      - name: Run app and extract OpenAPI spec
        run: |
          java -jar build/libs/*.jar &
          APP_PID=$!
          echo "Waiting for app startup..."
          sleep 15
          curl --fail http://localhost:8080/v3/api-docs.yaml -o openapi.yaml
          kill $APP_PID

      - name: Upload OpenAPI spec
        uses: actions/upload-artifact@v4
        with:
          name: openapi-spec
          path: openapi.yaml